# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

name: $(MajorVersion).$(MinorVersion).$(Date:yy)$(DayOfYear)$(Rev:.rr)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  netVersion: '6.x'

steps:
- task: DotNetCoreCLI@2
  displayName: "Restauraci贸n de dependencias"
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
    
- task: DotNetCoreCLI@2
  displayName: 'Compilaci贸n de soluci贸n'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Ejecuci贸n de tests'
  inputs:
    command: 'test'
    projects: '**/*Test*.csproj'
    arguments: '--configuration $(buildConfiguration)'

